trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm test
  displayName: 'npm test'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'

- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: 'Microsoft Partner Network(6de167de-c89d-44e4-8d1a-d441cb3f8f07)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'node-azure'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: './templates/template.json'
    csmParametersFile: './templates/parameters.json'
    deploymentMode: 'Complete'